name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  ci:
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, ghc: 9.2.1 }
          - { os: ubuntu-20.04, ghc: 9.0.1 }
          - { os: ubuntu-20.04, ghc: 8.10.7 }
          - { os: macos-11, ghc: 9.2.1 }
          - { os: macos-11, ghc: 9.0.1 }
          - { os: windows-2019, ghc: 9.0.1 }
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - run: mkdir artifact

      - run: mkdir artifact/${{ matrix.os }}

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.6.2.0

      - run: cabal configure --enable-tests --flags strict --jobs

      - run: cabal freeze

      - run: cat cabal.project.freeze

      - run: cp cabal.project.freeze artifact/${{ matrix.os }}

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-

      - run: cabal build

      - run: cabal test --test-show-details direct

      - run: cabal check

      - run: cabal sdist --output-dir artifact/${{ matrix.os }}

      - uses: actions/upload-artifact@v2
        with:
          name: hermes-json-${{ github.sha }}
          path: artifact

  release:
    needs: ci
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: hermes-json-${{ github.sha }}
          path: artifact

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/gzip
          asset_name: hermes-json-${{ github.event.release.tag_name }}.tar.gz
          asset_path: artifact/ubuntu-20.04/hermes-json-${{ github.event.release.tag_name }}.tar.gz
          upload_url: ${{ github.event.release.upload_url }}

      - run: cabal upload --publish --username '${{ secrets.HACKAGE_USERNAME }}' --password '${{ secrets.HACKAGE_PASSWORD }}' artifact/ubuntu-20.04/hermes-json-${{ github.event.release.tag_name }}.tar.gz
